stages:
    - install
    - build
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

install_dependencies:
    stage: install
    tags:
        - deploy
        - servertest
        - html
    script:
        - pnpm i
    only:
        - master

build:
    stage: build
    tags:
        - deploy
        - servertest
        - html
    script:
        - pnpm run build
    artifacts:
        paths:
            - build/
        expire_in: 120 minutes
    only:
        - master

deploy_on_servertest:
    stage: deploy
    when: manual
    only:
        - master
    tags:
        - deploy
        - html
        - servertest
    environment:
        name: servertest
    variables:
        DEPLOY_PATH: /var/www/servertest/data/www/fronttest.servertest.pro/
        DEPLOY_USER: servertest
        SERVERTEST_DOMAIN: fronttest.servertest.pro/
        SERVERTEST_USER: servertest
    script:
        - sudo -H -E ~/scripts/deploy/configure_server.sh
        - sudo -H -E ~/scripts/deploy/deploy_html.sh

